composer.json
src/BrowserKitDriver.php

Symfony 2.2 is EOLed since 1 year: http://symfony.com/roadmap?version=2.2#checker
I think we can be fine with dropping the support for it in the next minor version of the driver (1.3.0) rather than bumping the major version.
People using Mink inside Behat already lost the compatibility with these unmaintained Symfony versions anyway btw, and I don't think anyone should be using unmaintained versions, so it is acceptable IMO (people who don't update their Symfony dependency will be fine with not updating their Mink driver anyway)

Removed the BC layers for Symfony 2.2 and older

---

composer.json
src/BrowserKitDriver.php

Assume this HTML code:
````html
<div id="elem">
<script src="foo.js"></script>
<h2>Hello!</h2>
</div>
````
Using `$elem->getXml()` resulted in:
````xml
<script src="foo.js"/>
<h2>Hello!</h2>
````
Which is incorrect HTML and is interpreted by browsers as if `<script>` was never closed ([script tags are really weird in HTML](https://mathiasbynens.be/notes/etago)).
Using `$elem->getHtml()` results in correct HTML using `</script>`.

Use saveHTML to get correct HTML code back

---

.travis.yml
composer.json
src/BrowserKitDriver.php

my pull request on mink (https://github.com/minkphp/Mink/pull/681)  should be merge before this one.
I don't know how to keep compatibility with Symfony 2.3 (the getNode method was protected), but in Symfony 3.0 the Crawler don't extends the SplObjectStorage, so we can't retrieve the first DomElement with the same method

Allow installation of this driver with symfony3

---

.travis.yml

We want to test against the latest stable version (normal build), against LTS versions (because they are LTS) and against the dev version of dependencies.

Clean the list of Symfony versions

---

src/BrowserKitDriver.php

When updating the Mink codebase to follow the Symfony convention properly, I forgot to update this driver.

Update the deprecation warning convention

---

src/BrowserKitDriver.php
tests/Custom/ErrorHandlingTest.php

Symfony deprecated accessing `Client::getInternalRequest()` and `Client::getInternalResponse()` without first making `request()`. In Symfony 5+ it will throw exception so we're both handling the exception and deprecation messages in this PR.
Unfortunately, there's no way to avoid deprecation messages without tracking request on our end so I just marked a few tests as "legacy" that were testing this specific behaviour of accessing request/response without response first.

Handle Symfony 5+ behaviour for Client::getInternalRequest/getInternalResponse

---

.travis.yml

Removed HHVM since it's longer gonna be PHP compatible.
Added PHP 7.2 as the latest stable PHP version.

Remove HHVM support and add PHP 7.2

---

.travis.yml

The driver-testsuite package now depends on phpunit to force installing a version compatible with the driver testsuite.

Change Travis to use phpunit from vendors

---

src/BrowserKitDriver.php

As of 4.3, symfony/dom-crawler will automatically pick masterminds/html5 as the parser when it is installed and the HTML uses the HTML5 doctype. This provides better support for HTML5, but requires using the saveHTML() method of the library rather than of the DOMDocument to avoid weird edge cases.
Given that the Crawler methods dealing with HTML are already taking care of that, they are now used by the driver rather than using the DOMDocument API. The implementation of outerHTML still ships a fallback as the Crawler has the method only in 4.4+.

Improve compatibility with crawler in HTML5 mode

---

tests/BrowserKitConfig.php

The detection relied on detecting the test method added when introducing the feature in symfony/dom-crawler. But as of Symfony 4.4, tests are stripped from the dist archives. An additional detection based on a new method added in later Symfony version is now used to filter out the false positives (not detecting 4.4 and newer as being <3.3).
This code will be cleaned when dropping support for old Symfony versions, but I want to tag a release before doing that.

Fix the detection of HTML5 support in the testsuite

---

.travis.yml

This allows benefiting from the Travis cache, as the composer cache of downloaded archives is persisted between builds.

Install vendors with dist archives on Travis

---

src/BrowserKitDriver.php

The `getCookiePath()` function was assuming that the full path name of
the current URL includes the full filename - for example
`/sub-folder/index.php`.
However, where the browser visits the parent folder and the default file
is served (`/sub-folder/` serving `/sub-folder/index.php`) the wrong
current URL is returned.
This means that the deleteCookie function tries to delete for the parent
folder upwards, and where the cookie was set in a specific path, the
delete fails.
For example:
Given a cookie set with:
```
setcookie('somename', 'somevalue', 0, '/some/sub-folder/');
```
The following would fail:
```
$session->visit('/some/sub-folder/');
$session->setCookie('somename', null);
```
The `setCookie` call would call `deleteCookie`, which fetches the URL to
delete. The `getCookiePath()` …

Delete cookie in subpath correctly

---

.github/workflows/tests.yml
phpunit.http_client.xml
src/BrowserKitDriver.php
tests/AbstractBrowserKitConfig.php
tests/HttpClientBrowserKitConfig.php
tests/HttpKernelBrowserKitConfig.php

This BrowserKit implementation is the successor of Goutte (Goutte 4.x is only extending that class under the `Goutte\Client` name without any change). This makes sure we support it.
The new dependencies are not added as dev requirements for now due to the min PHP version (Symfony 4.4 requires PHP 7.1+). This will change once support for those old versions is dropped.

Add a CI job using the HttpBrowser of BrowserKit and HttpClient

---

phpunit.http_client.xml
phpunit.xml.dist
tests/Custom/ErrorHandlingTest.php

When the simple-phpunit script is not used, the test listener is not registered magically by symfony/phpunit-bridge in recent PHPUnit versions. It needs to be registered explicitly.

Improve the reporting of deprecations in the testsuite

---

src/BrowserKitDriver.php

This is necessary to make Psalm checks pass at https://github.com/FriendsOfBehat/SymfonyExtension/pull/195.

Fix (by removing) an outdated docblock type hint

---

.github/workflows/tests.yml

this is useful if we want to try a new version of the driver testsuite with the driver.

Add the possibility to trigger a CI run manually

---

src/BrowserKitDriver.php

Check for unsupported types but let the rest.
Fixes #172

Check for the actual types that are not allowed

---

src/BrowserKitDriver.php

https://github.com/minkphp/driver-testsuite/pull/78 and https://github.com/minkphp/driver-testsuite/pull/79 have improved the testsuite coverage for invalid values. This ensures that those tests pass.

Fix the validation of invalid values in tests

---

src/BrowserKitDriver.php

See https://github.com/minkphp/driver-testsuite/issues/98.
Static analysis issues are not related.

Normalize behavior of "getText" method

---

src/BrowserKitDriver.php

Fixes a test failure for a test, that is introduced in the https://github.com/minkphp/driver-testsuite/pull/102 .
P.S.
The static analysis failures are unrelated.

Throw exception, when doing a "setValue" call on checkbox with a non-boolean value
